@tag
Feature: Abertura Contas Nubank

  @tag1
  Scenario: PJ
Given que acesse a url "https://www.nubank.com.br"
And NO CABEÇALHO SELECIONE PARA SEU NEGOCIO
And CLICAR EM CONTA PJ
And PREENCHER O CAMPO CNPJ DA EMPRESA
And CLICAR EM ABRIR CONTA PJ
And PREENCHER O FORMULARIO DE ABERTURA DE CONTA
And SELECIONAR CHECKBOX POLITICAS DE PRIVACIDADE
When CLICAR EM ENVIAR
Then APARECERÁ O TEXTO